// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArx7lMw_iHnGuWE6YPkbcKTZOF9td4j4o',
    appId: '1:126152671266:web:60862c41a2aeed39a48a7b',
    messagingSenderId: '126152671266',
    projectId: 'cajangfinance',
    authDomain: 'cajangfinance.firebaseapp.com',
    storageBucket: 'cajangfinance.appspot.com',
    measurementId: 'G-HEVMXBREBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDOraaszRQSHo23s-bX58RRYxUCEfLFY',
    appId: '1:126152671266:android:7dbee85c4c319323a48a7b',
    messagingSenderId: '126152671266',
    projectId: 'cajangfinance',
    storageBucket: 'cajangfinance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJxWK2qWm0hNFm2-tUkMxSCI8BXkL6-P8',
    appId: '1:126152671266:ios:be60f5d9bc14631aa48a7b',
    messagingSenderId: '126152671266',
    projectId: 'cajangfinance',
    storageBucket: 'cajangfinance.appspot.com',
    iosClientId: '126152671266-5js0lh16t2vsqah9pbj0juuiunl225uq.apps.googleusercontent.com',
    iosBundleId: 'com.amal.cajang',
  );
}
